### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by andreas-groos** [djdefi/rss-firehose#11]
What's your idea for adding styling? I had a look at the code and given that it's just HTML templating I could do some extra styling.

**Comment by djdefi** [comment]
So I based the current style heavily on http://lite.cnn.com/en - I want to try to keep this simple / accessible on slow connections and simple browsers (feature phones etc). 

The main thing I am considering so far is in-lining the styles rather than having an external stylesheet.

I am open to ideas though, keeping the lightweight / low bandwidth goal in mind
